name: Purge cache

on:
  push:
    branches:
    - main

jobs:
  purge-cache:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Purge cache
        run: |
          curl \
          -X POST \
          "https://api.bunny.net/pullzone/${{ secrets.BUNNYCDN_DOCS_PULLZONE_ID }}/purgeCache" \
          -H "AccessKey: ${{ secrets.BUNNYCDN_SECRET }}" \
          -H "content-type: application/json"
